version: "3.8"
services:

  server:
    restart: always
    build: server
    ports:
      - "3000:3000"
    networks:
      - backend
    container_name: fdj-server-container
    volumes:
      - "/usr/src/app/node_modules"
      - "./server:/usr/src/app/"

  db:
    image: mongo:4.2
    ports:
      - "27017:27017"
    networks:
      - backend
    container_name: fdj-db-container
    volumes:
      - "./db/sports:/dump"

  app:
    restart: always
    build: app
    ports:
      - "4200:4200"
      - "49153:49153"
    networks:
      - frontend
    container_name: fdj-app-container
    volumes:
      - "/usr/src/app/node_modules"
      - "./app:/usr/src/app/"

networks:
  frontend:
  backend:

volumes:
  dump:
